from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Image
)

from reportlab.lib.styles import getSampleStyleSheet

from datetime import datetime


def create_pdf_report(
    filename,
    disease,
    confidence,
    patient_name,
    patient_age,
    patient_gender,
    xray_path=None,
    heatmap_path=None
):

    pdf = SimpleDocTemplate(filename)

    styles = getSampleStyleSheet()

    content = []

    # =========================
    # TITLE
    # =========================

    title = Paragraph(
        "AI Lung Disease Detection Report",
        styles["Title"]
    )

    content.append(title)

    content.append(Spacer(1, 20))

    # =========================
    # DATE
    # =========================

    current_time = datetime.now().strftime(
        "%d-%m-%Y %H:%M:%S"
    )

    content.append(
        Paragraph(
            f"<b>Date:</b> {current_time}",
            styles["Normal"]
        )
    )

    # =========================
    # PATIENT DETAILS
    # =========================

    content.append(
        Paragraph(
            f"<b>Patient Name:</b> {patient_name}",
            styles["Normal"]
        )
    )

    content.append(
        Paragraph(
            f"<b>Age:</b> {patient_age}",
            styles["Normal"]
        )
    )

    content.append(
        Paragraph(
            f"<b>Gender:</b> {patient_gender}",
            styles["Normal"]
        )
    )

    content.append(Spacer(1, 10))

    # =========================
    # PREDICTION
    # =========================

    content.append(
        Paragraph(
            f"<b>Prediction:</b> {disease}",
            styles["Normal"]
        )
    )

    content.append(
        Paragraph(
            f"<b>Confidence:</b> {confidence:.2f}%",
            styles["Normal"]
        )
    )

    content.append(Spacer(1, 20))

    # =========================
    # X-RAY IMAGE
    # =========================

    if xray_path:

        content.append(
            Paragraph(
                "<b>Uploaded X-ray</b>",
                styles["Heading2"]
            )
        )

        content.append(
            Image(
                xray_path,
                width=250,
                height=250
            )
        )

        content.append(
            Spacer(1, 20)
        )

    # =========================
    # HEATMAP IMAGE
    # =========================

    if heatmap_path:

        content.append(
            Paragraph(
                "<b>Grad-CAM Heatmap</b>",
                styles["Heading2"]
            )
        )

        content.append(
            Image(
                heatmap_path,
                width=250,
                height=250
            )
        )

        content.append(
            Spacer(1, 20)
        )

    # =========================
    # BLOOD REPORT INDICATORS
    # =========================

    content.append(
        Paragraph(
            "<b>Typical Blood Report Indicators</b>",
            styles["Heading2"]
        )
    )

    if disease == "COVID":

        content.append(
            Paragraph(
                "CRP: Elevated | D-Dimer: Elevated | Lymphocyte Count: Reduced",
                styles["Normal"]
            )
        )

    elif disease == "PNEUMONIA":

        content.append(
            Paragraph(
                "WBC Count: Elevated | CRP: Elevated | ESR: Elevated | Hemoglobin: Normal / Slightly Low",
                styles["Normal"]
            )
        )

    elif disease == "TB":

        content.append(
            Paragraph(
                "ESR: High | CRP: Elevated | Hemoglobin: Mildly Reduced | WBC Count: Mildly Elevated",
                styles["Normal"]
            )
        )

    else:

        content.append(
            Paragraph(
                "Blood parameters are typically within normal limits.",
                styles["Normal"]
            )
        )

    content.append(Spacer(1, 20))

    # =========================
    # DISCLAIMER
    # =========================

    content.append(
        Paragraph(
            "This report is generated by an AI system and is intended for educational and research purposes only.",
            styles["Italic"]
        )
    )

    content.append(
        Paragraph(
            "Generated using CNN + Attention U-Net + Grad-CAM",
            styles["Italic"]
        )
    )

    # =========================
    # BUILD PDF
    # =========================

    pdf.build(content)